name: publish

on:
  workflow_dispatch:
  
permissions:
  contents: write

env:
  NOTION_URL: https://branched-almandine-09d.notion.site/Hi-I-m-Tobias-acc5478907ef47cf847383e2d1471121?pvs=74
  NOTION_TITLE: hi-i-m-tobias

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-notion-snapshot
        uses: actions/checkout@v3
        with:
          repository: tobiasleibrock/notionSnapshot # use fork while waiting for patch pr (sueszli/notionSnapshot)
          path: notion-snapshot
      - name: checkout-this-repo
        uses: actions/checkout@v3
        with:
          path: repo
      - name: install-notion-snapshot-requirements
        run: pip install -r notion-snapshot/requirements.txt
      - name: patch-notion-snapshot
        run: |
          pip install --upgrade webdriver_manager
      - name: run-notion-snapshot
        run: |
          python3 notion-snapshot/notionsnapshot -t 3 $NOTION_URL
      - name: push-github-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          export GIT_DEPLOY_DIR="../snapshots/$NOTION_TITLE"
          export GIT_DEPLOY_BRANCH=gh-pages
          export GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git"
          bash deploy.sh
        working-directory: repo