name: publish

on:
  workflow_dispatch:
  
permissions:
  contents: write

env:
  NOTION_URL: https://branched-almandine-09d.notion.site/Hi-I-m-Tobias-acc5478907ef47cf847383e2d1471121?pvs=74

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-notion-snapshot
        uses: actions/checkout@v3
        with:
          repository: sueszli/notionSnapshot
          path: notion-snapshot
      - name: checkout-this-repo
        uses: actions/checkout@v3
        with:
          path: pages_repo
      - name: install-notion-snapshot-requirements
        run: pip install -r notion-snapshot/requirements.txt
      - name: patch-notion-snapshot
        run: |
          pip install --upgrade webdriver_manager
      - name: run-notion-snapshot
        run: |
          python3 notion-snapshot/notionsnapshot $NOTION_URL
      - name: push-github-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../notion-snapshot/snapshots/* \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo